// ==========================================
// MASTER CHORE SCHEDULE CONFIGURATION
// ==========================================
const choreSchedule = {
  days: {
    Monday: [
      "Kitchen: Wipe microwave",
      "Kitchen: Wash dishes",
      "Kitchen: Rinse sink",
      "Kitchen: Wipe counters and stovetop",
      "Kitchen: Meal prep",
      "Main Bathrooms: Wipe counters",
      "Main Bathrooms: Rinse sink",
      "Main Bathrooms: Wipe toilet seats",
      "Main Bathrooms: Take a shower",
      "Basement: Empty dehumidifier",
      "Basement: Clear steps",
      "Basement: Cycle laundry",
    ],
    Tuesday: [
      "Kitchen: Wash dishes",
      "Kitchen: Rinse sink",
      "Kitchen: Wipe counters and stovetop",
      "Kitchen: Take out garbage",
      "Kitchen: Meal prep",
      "Main Bathrooms: Wipe mirrors",
      "Main Bathrooms: Wipe counters",
      "Main Bathrooms: Rinse sink",
      "Main Bathrooms: Clean toilets",
      "Main Bathrooms: Take a shower",
      "Upstairs Bathroom: Wipe sink",
      "Upstairs Bathroom: Clean toilet",
      "Basement: Empty dehumidifier",
      "Basement: Clear steps",
      "Basement: Cycle laundry",
    ],
    Wednesday: [
      "Kitchen: Wash dishes",
      "Kitchen: Rinse sink",
      "Kitchen: Wipe counters and stovetop",
      "Kitchen: Take out recycling",
      "Kitchen: Vacuum floor",
      "Kitchen: Meal prep",
      "Main Bathrooms: Wipe mirrors",
      "Main Bathrooms: Wipe counters",
      "Main Bathrooms: Rinse sink",
      "Main Bathrooms: Clean toilets",
      "Main Bathrooms: Take a shower",
      "Basement: Empty dehumidifier",
      "Basement: Clear steps",
      "Basement: Cycle laundry",
    ],
    Thursday: [
      "Kitchen: Wash dishes",
      "Kitchen: Rinse sink",
      "Kitchen: Wipe counters and stovetop",
      "Kitchen: Meal prep",
      "Main Bathrooms: Wipe counters",
      "Main Bathrooms: Rinse sink",
      "Main Bathrooms: Wipe toilet seats",
      "Main Bathrooms: Take a shower",
      "Upstairs Bathroom: Wipe sink",
      "Upstairs Bathroom: Clean toilet",
      "Basement: Empty dehumidifier",
      "Basement: Clear steps",
      "Basement: Cycle laundry",
      "Master Bedroom: Change the bed sheets",
      "Master Bedroom: Wash bed sheets",
      "Master Bedroom: Bedroom declutter",
      "Pool: Shock the pool",
    ],
    Friday: [
      "Kitchen: Wash dishes",
      "Kitchen: Rinse sink",
      "Kitchen: Wipe counters and stovetop",
      "Kitchen: Meal prep",
      "Main Bathrooms: Wipe counters",
      "Main Bathrooms: Rinse sink",
      "Main Bathrooms: Wipe toilet seats",
      "Main Bathrooms: Take a shower",
      "Basement: Empty dehumidifier",
      "Basement: Clear steps",
      "Basement: Cycle laundry",
      "Whole House: Clean glass doors",
    ],
    Saturday: [
      "Kitchen: Clean refrigerator",
      "Kitchen: Wash dishes",
      "Kitchen: Rinse sink",
      "Kitchen: Wipe counters and stovetop",
      "Kitchen: Mop floor",
      "Kitchen: Meal plan and order groceries",
      "Main Bathrooms: Wipe counters",
      "Main Bathrooms: Rinse sink",
      "Main Bathrooms: Clean toilets",
      "Main Bathrooms: Mop floors",
      "Main Bathrooms: Take a shower",
      "Upstairs Bathroom: Wipe sink",
      "Upstairs Bathroom: Clean toilet",
      "Basement: Empty dehumidifier",
      "Basement: Clear steps",
      "Basement: Cycle laundry",
      "Whole House: Declutter",
      "Whole House: Dust",
      "Whole House: Vacuum",
    ],
    Sunday: ["Groom", "Finish laundry", "Prepare for the work week", "Catch anything that needs attention"],
  },
  monthlyRotation: {
    weeks: {
      1: ["Clean showers", "Test smoke detectors", "Groom dogs"],
      2: ["Sweep & declutter garage", "Declutter basement"],
      3: ["Clean upstairs bedrooms and bathrooms"],
      4: ["Organize pantry, drawers, and cabinets"],
      5: ["Clean windows", "Clean baseboards and door frames", "Clean under the couch"],
    },
  },
  yearly: {
    January: ["Clean washing machine pump"],
    February: ["Clean under the stove and refrigerator"],
    March: ["Change/clean furnace filters", "Apply pest control"],
    April: ["Change water filters"],
    May: [],
    June: ["Change/clean furnace filters"],
    July: ["Make soap"],
    August: [],
    September: ["Change/clean furnace filters"],
    October: ["Clean oven"],
    November: ["Check windows and doors for drafts"],
    December: ["Change/clean furnace filters"],
  },
};
